baseURL: 'http://example.org/'
languageCode: 'ja-JP'
theme: ['landing-pages', 'andaze']
title: 'アンダーズ株式会社'




markup:
  goldmark:
    renderer:
      unsafe: true

params:
  contactIcon: "images/envelope.png"
  smtpjs:
    secureToken: 22152f6c-a021-4af1-90d4-cd093adb07c0 # dev,localhost
    fromMail: "contact@andaze.com"
    bccMail: "nishidai@andaze.com,contact-us@andaze.com,contact-us@andaze.com,d@solutus.jp"
    subject: "お問い合わせいただきありがとうございます。"
    confirmMessage:
      alert: "お問い合わせいただきありがとうざいます。"
      bodyHeader: "お問い合わせいただきありがとうざいます。"
      bodyFooter: "上記の内容にてお問い合わせを受け付けました。<br/>追って担当者から回答させていただきます。"