baseURL: 'http://example.org/'
languageCode: 'en-us'
theme: ['landing-pages', 'andaze']
title: 'My New Hugo Site'

params:
  smtpjs:
    # secureToken: "978913ea-4f2e-4803-9ec7-05bd3fe8e6cb" # Created accounts at https://app.elasticemail.com/marketing/settings/new/manage-smtp, Encrypt at https://smtpjs.com/
    secureToken: 22152f6c-a021-4af1-90d4-cd093adb07c0 # dev,localhost
    fromMail: "no-reply@andaze.com"
    bccMail: "nishidai@andaze.com,contact-us@andaze.com,d@solutus.jp"
    subject: "お問い合わせいただきありがとうございます。"
    confirmMessage:
      alert: "お問い合わせいただきありがとうざいます。"
      bodyHeader: "お問い合わせいただきありがとうざいます。"
      bodyFooter: "上記の内容にてお問い合わせを受け付けました。<br/>追って担当者から回答させていただきます。"