---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: _index.md
  label: home
- type: directory
  path: chapters
  label: chapters
  create: all
  match: "**/*"
- type: directory
  path: faq
  label: faq
  create: all
  match: "**/*"
- type: directory
  path: key-visual
  label: key-visual
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
